language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-29
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.3
    - $ANDROID_TARGET
    - extra-android-m2repository
    - extra-google-m2repository
script:
  - ./gradlew build